### ISSUE TITLE
Design : 결과 페이지 

### ISSUE THREAD

**Issue by Ryan-Dia** [jamanchi/jamanchi-front#32]
## ✅ Implement TODO
- [x]  설명이 길어지면 설명 카드가 커져서 버튼도 같이 내려감
 해결 ex) 모달창

<img width="401" alt="image" src="https://github.com/jamanchi/jamanchi-front/assets/76567238/ba3d49e4-1883-4bae-ba00-cedd1e492dd8">

## 📚 Remarks

**Comment by tnghgks** [comment]
PR #35 에 수정해서 올렸습니다!
![cap](https://github.com/jamanchi/jamanchi-front/assets/17325845/3cc280f9-0085-4de1-a543-575fef9dbb7c)
